name: Release
on:
  push:
    tags:
      - "v*"
      - "!v*-rc*"

permissions:
  contents: write
jobs:
  pre_release_lmml:
    name: Publish Release LMML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Copy GSX profile
        run: |
          cp -r ./LMML-vikingstudios-malta.ini ./Packages
      - name: Build ZIP file
        run: |
          mkdir -p Packages-Out/
          7z a ../Packages-Out/vikingstudios-airport-lmml-malta.zip ./Packages/*
          cd ../..
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.4    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          files: ../Packages-Out/vikingstudios-airport-lmml-malta.zip
